# Use Eclipse Temurin Java image for JDK 17
FROM eclipse-temurin:17-jdk

# Set working directory
WORKDIR /app

# Copy everything to container
COPY . .

# Build the project (if you’re using wrapper)
RUN ./mvnw package -DskipTests

# Run the jar file
CMD ["java", "-jar", "target/To-Do_App-0.0.1-SNAPSHOT.jar"]